/* eslint-disable */
require('./approval')
require('./email')
require('./facebook')
require('./instagram')
require('./lightbulb-on-outline')
require('./linkedin')
require('./phone')
require('./twitter')
require('./weight')
